trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Build Project'

- script: |
    # Ensure versioning increments with the Build ID
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack NuGet Package with Auto Versioning'

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    nuGetFeedType: external
    externalFeedUrl: 'https://pkgs.dev.azure.com/ssanto43/_packaging/Lab4Feed/nuget/v3/index.json'
    externalFeedCredentials: 'System.AccessToken'
  displayName: 'Push to Azure Artifacts Feed using URL'