trigger:
  branches:
    include:
      - main

pool:
  name: StephAgentPool

steps:
# Build and pack StringLibrary
- script: |
    dotnet restore "StringLibrary\StringLibrary.csproj"
    dotnet build "StringLibrary\StringLibrary.csproj" --configuration Release
    dotnet pack "StringLibrary\StringLibrary.csproj" --configuration Release --output "$(Build.ArtifactStagingDirectory)" /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack StringLibrary NuGet Package'

# Build and pack ShowCase
- script: |
    dotnet restore "ShowCase\ShowCase.csproj"
    dotnet build "ShowCase\ShowCase.csproj" --configuration Release
    dotnet pack "ShowCase\ShowCase.csproj" --configuration Release --output "$(Build.ArtifactStagingDirectory)" /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack ShowCase NuGet Package'

# Push both packages to Azure Artifacts Feed
- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
    nuGetFeedType: internal
    publishVstsFeed: 'Lab4  Azure DevOps CICD/Lab4Feed'
  displayName: 'Push to Azure Artifacts Feed'