trigger:
  branches:
    include:
      - main

pool:
  name: StephAgentPool

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '9.0.x'
    installationPath: 'C:\Program Files\dotnet'

- script: |
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Build Project'

- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack NuGet Package with Auto Versioning'

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
    nuGetFeedType: internal
    publishVstsFeed: 'Lab4  Azure DevOps CICD/stephLab4Feed'
  displayName: 'Push to Azure Artifacts Feed'