trigger:
  branches:
    include:
      - main

pool:
  name: StephAgentPool # Your agent pool

steps:
  # Build the project
  - script: |
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Build Project'

  # Pack NuGet Package with Auto Versioning
  - script: |
      dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:Version=1.0.$(Build.BuildId)
    displayName: 'Pack NuGet Package with Auto Versioning'

  # Authenticate with Azure Artifacts using System.AccessToken
  - script: |
      dotnet nuget add source https://pkgs.dev.azure.com/ssanto43/4d45d84f-b2b7-4367-bb29-4b45d2463fc5/_packaging/Lab4Feed/nuget/v3/index.json \
          --name Lab4Feed --username <empty> --password $(System.AccessToken) --store-password-in-clear-text
    displayName: 'Configure NuGet Authentication'
    env:
      VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/ssanto43/4d45d84f-b2b7-4367-bb29-4b45d2463fc5/_packaging/Lab4Feed/nuget/v3/index.json","password":"$(System.AccessToken)"}]}'

  # Push to Azure Artifacts Feed
  - task: NuGetCommand@2
    inputs:
      command: push
      packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
      nuGetFeedType: internal
      publishVstsFeed: 'Lab4 Azure DevOps CICD/stephLab4Feed'
    displayName: 'Push to Azure Artifacts Feed'